# Generated by Django 3.1.7 on 2021-03-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_activity_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='pretty_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
